include:
  - project: 'wiremind/gitlab-ci-common'
    ref: 'v10.1.1'
    file: 'gitlab-ci-common-platform.yml'

variables:
  EGG_NAME: wiremind-kubernetes
  PACKAGE_NAME: wiremind_kubernetes
  SRC_DIR: src

e2e-tests:
  extends: .platform-e2e-test
