include:
  - project: 'wiremind/gitlab-ci-common'
    ref: 'master'
    file: 'abstract.yml'
  - project: 'wiremind/gitlab-ci-common'
    ref: 'master'
    file: 'libraries/platform.yml'

variables:
  EGG_NAME: wiremind-kubernetes
  PACKAGE_NAME: wiremind_kubernetes
  SRC_DIR: src
  DOCKER_BASE_IMAGE: python:3.7

conventional-commits:
  allow_failure: true

e2e-tests:
  extends: .platform-e2e-test


.test:
  # Note: Extends abstract.yml
  variables:
    TEST_DIR: src/$PACKAGE_NAME/tests/unit_tests
