# Allows to define "expected deployment scale" so that one can reset the
# number of Pods for a deployment to the expected amount if it has manually been changed

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: expecteddeploymentscales.wiremind.io
spec:
  group: wiremind.io
  scope: Namespaced
  names:
    plural: expecteddeploymentscales
    singular: expecteddeploymentscale
    kind: ExpectedDeploymentScale
    shortNames:
      - eds
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            deploymentName:
              type: string
            expectedScale:
              type: integer
            priority:
              type: integer
              # default: 0  # Only available in CRD v1
          allOf:
          - required: ["deploymentName", "expectedScale"]
  additionalPrinterColumns:
  - name: Deployment Name
    type: string
    description: The name of the Deployment under control
    JSONPath: .spec.deploymentName
  - name: Expected Scale
    type: integer
    description: The expected Scale for the Deployment under control
    JSONPath: .spec.expectedScale
  - name: Priority
    type: integer
    description: |
      The priority of the Deployment under control for scale down order.

      wiremind-kubernetes will, for each different priority found for all considered ExpectedDeploymentScale,
      scale down all deployments with a given priority, then wait for their pods to be actually deleted,
      then continue with the next priority (in descending order).

      Higher priority means that the Deployment will be scaled down before others with lower priority.
    JSONPath: .spec.priority
